<?php
namespace Transom\SiftModule\Block\Adminhtml\Index\Configuration;



/**
 * Class Ranges
 */
class Gateway implements \Magento\Framework\Option\ArrayInterface
{
    /**
     * Prepare rendering the new field by adding all the needed columns
     */


    public function __construct()
    {

    }

    public function toOptionArray()
    {

        return [
            ['value' => '$acapture', 'label' => __('Acapture')],
            ['value' => '$adyen', 'label' => __('Adyen')],
            ['value' => '$affipay', 'label' => __('Affipay')],
            ['value' => '$affirm', 'label' => __('Affirm')],
            ['value' => '$afterpay', 'label' => __('Afterpay')],
            ['value' => '$alipay', 'label' => __('Alipay')],
            ['value' => '$altapay', 'label' => __('Altapay')],
            ['value' => '$amazon_payments', 'label' => __('Amazon Payments')],
            ['value' => '$android_iap', 'label' => __('Android Iap')],
            ['value' => '$android_pay', 'label' => __('Android Pay')],
            ['value' => '$apple_iap', 'label' => __('Apple Iap')],
            ['value' => '$apple_pay', 'label' => __('Apple Pay')],
            ['value' => '$astropay', 'label' => __('Astropay')],
            ['value' => '$authorizenet', 'label' => __('Authorizenet')],
            ['value' => '$avangate', 'label' => __('Avangate')],
            ['value' => '$balanced', 'label' => __('Balanced')],
            ['value' => '$banorte', 'label' => __('Banorte')],
            ['value' => '$banwire', 'label' => __('Banwire')],
            ['value' => '$barclays', 'label' => __('Barclays')],
            ['value' => '$beanstream', 'label' => __('Beanstream')],
            ['value' => '$billdesk', 'label' => __('Billdesk')],
            ['value' => '$bitgo', 'label' => __('Bitgo')],
            ['value' => '$bitpay', 'label' => __('Bitpay')],
            ['value' => '$blockchain', 'label' => __('Blockchain')],
            ['value' => '$bluepay', 'label' => __('Bluepay')],
            ['value' => '$bluesnap', 'label' => __('Bluesnap')],
            ['value' => '$bnpparibas', 'label' => __('Bnpparibas')],
            ['value' => '$boacompra', 'label' => __('Boacompra')],
            ['value' => '$bpay', 'label' => __('Bpay')],
            ['value' => '$braintree', 'label' => __('Braintree')],
            ['value' => '$bread', 'label' => __('Bread')],
            ['value' => '$buckaroo', 'label' => __('Buckaroo')],
            ['value' => '$cardconnect', 'label' => __('Cardconnect')],
            ['value' => '$ccavenue', 'label' => __('Ccavenue')],
            ['value' => '$chain_commerce', 'label' => __('Chain Commerce')],
            ['value' => '$chase_paymentech', 'label' => __('Chase Paymentech')],
            ['value' => '$checkoutcom', 'label' => __('Checkoutcom')],
            ['value' => '$cielo', 'label' => __('Cielo')],
            ['value' => '$citrus_pay', 'label' => __('Citrus Pay')],
            ['value' => '$clearsettle', 'label' => __('Clearsettle')],
            ['value' => '$clearcommerce', 'label' => __('Clearcommerce')],
            ['value' => '$cloudpayments', 'label' => __('Cloudpayments')],
            ['value' => '$cofinoga', 'label' => __('Cofinoga')],
            ['value' => '$coinbase', 'label' => __('Coinbase')],
            ['value' => '$collector', 'label' => __('Collector')],
            ['value' => '$compropago', 'label' => __('Compropago')],
            ['value' => '$commweb', 'label' => __('Commweb')],
            ['value' => '$conekta', 'label' => __('Conekta')],
            ['value' => '$credsystem', 'label' => __('Credsystem')],
            ['value' => '$cuentadigital', 'label' => __('Cuentadigital')],
            ['value' => '$culqi', 'label' => __('Culqi')],
            ['value' => '$cybersource', 'label' => __('Cybersource')],
            ['value' => '$datacash', 'label' => __('Datacash')],
            ['value' => '$dbs_paylah', 'label' => __('Dbs Paylah')],
            ['value' => '$debitway', 'label' => __('Debitway')],
            ['value' => '$democracy_engine', 'label' => __('Democracy Engine')],
            ['value' => '$dibs', 'label' => __('Dibs')],
            ['value' => '$digital_river', 'label' => __('Digital River')],
            ['value' => '$dlocal', 'label' => __('Dlocal')],
            ['value' => '$dotpay', 'label' => __('Dotpay')],
            ['value' => '$dragonpay', 'label' => __('Dragonpay')],
            ['value' => '$dwolla', 'label' => __('Dwolla')],
            ['value' => '$ebanx', 'label' => __('Ebanx')],
            ['value' => '$ecopayz', 'label' => __('Ecopayz')],
            ['value' => '$edgil_payway', 'label' => __('Edgil Payway')],
            ['value' => '$elavon', 'label' => __('Elavon')],
            ['value' => '$empcorp', 'label' => __('Empcorp')],
            ['value' => '$epayeu', 'label' => __('Epayeu')],
            ['value' => '$eprocessing_network', 'label' => __('Eprocessing Network')],
            ['value' => '$esitef', 'label' => __('Esitef')],
            ['value' => '$euteller', 'label' => __('Euteller')],
            ['value' => '$everypay', 'label' => __('Everypay')],
            ['value' => '$eway', 'label' => __('Eway')],
            ['value' => '$e_xact', 'label' => __('E Xact')],
            ['value' => '$fxpaygate', 'label' => __('Fxpaygate')],
            ['value' => '$first_atlantic_commerce', 'label' => __('First Atlantic Commerce')],
            ['value' => '$first_data', 'label' => __('First Data')],
            ['value' => '$flutterwave', 'label' => __('Flutterwave')],
            ['value' => '$g2apay', 'label' => __('G2Apay')],
            ['value' => '$geoswift', 'label' => __('Geoswift')],
            ['value' => '$getnet', 'label' => __('Getnet')],
            ['value' => '$giropay', 'label' => __('Giropay')],
            ['value' => '$globalcollect', 'label' => __('Globalcollect')],
            ['value' => '$global_payments', 'label' => __('Global Payments')],
            ['value' => '$global_payways', 'label' => __('Global Payways')],
            ['value' => '$gmopg', 'label' => __('Gmopg')],
            ['value' => '$gocardless', 'label' => __('Gocardless')],
            ['value' => '$gocoin', 'label' => __('Gocoin')],
            ['value' => '$google_pay', 'label' => __('Google Pay')],
            ['value' => '$hdfc_fssnet', 'label' => __('Hdfc Fssnet')],
            ['value' => '$hipay', 'label' => __('Hipay')],
            ['value' => '$i2c', 'label' => __('I2C')],
            ['value' => '$ideal', 'label' => __('Ideal')],
            ['value' => '$ikajo', 'label' => __('Ikajo')],
            ['value' => '$ingenico', 'label' => __('Ingenico')],
            ['value' => '$instamojo', 'label' => __('Instamojo')],
            ['value' => '$interac', 'label' => __('Interac')],
            ['value' => '$internetsecure', 'label' => __('Internetsecure')],
            ['value' => '$intuit_quickbooks_payments', 'label' => __('Intuit Quickbooks Payments')],
            ['value' => '$isignthis', 'label' => __('Isignthis')],
            ['value' => '$iugu', 'label' => __('Iugu')],
            ['value' => '$iyzico', 'label' => __('Iyzico')],
            ['value' => '$jabong', 'label' => __('Jabong')],
            ['value' => '$juspay', 'label' => __('Juspay')],
            ['value' => '$kash', 'label' => __('Kash')],
            ['value' => '$klarna', 'label' => __('Klarna')],
            ['value' => '$kushki', 'label' => __('Kushki')],
            ['value' => '$lemonway', 'label' => __('Lemonway')],
            ['value' => '$limelight', 'label' => __('Limelight')],
            ['value' => '$logon', 'label' => __('Logon')],
            ['value' => '$mastercard_payment_gateway', 'label' => __('Mastercard Payment Gateway')],
            ['value' => '$masterpass', 'label' => __('Masterpass')],
            ['value' => '$maxipago', 'label' => __('Maxipago')],
            ['value' => '$maxpay', 'label' => __('Maxpay')],
            ['value' => '$meikopay', 'label' => __('Meikopay')],
            ['value' => '$mercadopago', 'label' => __('Mercadopago')],
            ['value' => '$merchant_esolutions', 'label' => __('Merchant Esolutions')],
            ['value' => '$midtrans', 'label' => __('Midtrans')],
            ['value' => '$mirjeh', 'label' => __('Mirjeh')],
            ['value' => '$moip', 'label' => __('Moip')],
            ['value' => '$mollie', 'label' => __('Mollie')],
            ['value' => '$moneris_solutions', 'label' => __('Moneris Solutions')],
            ['value' => '$moneygram', 'label' => __('Moneygram')],
            ['value' => '$mpesa', 'label' => __('Mpesa')],
            ['value' => '$multibanco', 'label' => __('Multibanco')],
            ['value' => '$netbilling', 'label' => __('Netbilling')],
            ['value' => '$netregistry', 'label' => __('Netregistry')],
            ['value' => '$neteller', 'label' => __('Neteller')],
            ['value' => '$network_for_good', 'label' => __('Network For Good')],
            ['value' => '$nicepay', 'label' => __('Nicepay')],
            ['value' => '$nmcryptgate', 'label' => __('Nmcryptgate')],
            ['value' => '$nmi', 'label' => __('Nmi')],
            ['value' => '$ogone', 'label' => __('Ogone')],
            ['value' => '$okpay', 'label' => __('Okpay')],
            ['value' => '$omise', 'label' => __('Omise')],
            ['value' => '$openpaymx', 'label' => __('Openpaymx')],
            ['value' => '$optimal_payments', 'label' => __('Optimal Payments')],
            ['value' => '$pagar_me', 'label' => __('Pagar Me')],
            ['value' => '$pagoefectivo', 'label' => __('Pagoefectivo')],
            ['value' => '$pagofacil', 'label' => __('Pagofacil')],
            ['value' => '$pagseguro', 'label' => __('Pagseguro')],
            ['value' => '$paxum', 'label' => __('Paxum')],
            ['value' => '$pay_garden', 'label' => __('Pay Garden')],
            ['value' => '$pay_zone', 'label' => __('Pay Zone')],
            ['value' => '$payease', 'label' => __('Payease')],
            ['value' => '$payeer', 'label' => __('Payeer')],
            ['value' => '$payeezy', 'label' => __('Payeezy')],
            ['value' => '$payfast', 'label' => __('Payfast')],
            ['value' => '$payflow', 'label' => __('Payflow')],
            ['value' => '$paygate', 'label' => __('Paygate')],
            ['value' => '$payjunction', 'label' => __('Payjunction')],
            ['value' => '$paylike', 'label' => __('Paylike')],
            ['value' => '$paymentwall', 'label' => __('Paymentwall')],
            ['value' => '$payment_express', 'label' => __('Payment Express')],
            ['value' => '$paymill', 'label' => __('Paymill')],
            ['value' => '$payone', 'label' => __('Payone')],
            ['value' => '$payoneer', 'label' => __('Payoneer')],
            ['value' => '$paypal', 'label' => __('Paypal')],
            ['value' => '$paypal_express', 'label' => __('Paypal Express')],
            ['value' => '$paysafe', 'label' => __('Paysafe')],
            ['value' => '$paysafecard', 'label' => __('Paysafecard')],
            ['value' => '$paysera', 'label' => __('Paysera')],
            ['value' => '$paysimple', 'label' => __('Paysimple')],
            ['value' => '$paystation', 'label' => __('Paystation')],
            ['value' => '$paytm', 'label' => __('Paytm')],
            ['value' => '$paytrace', 'label' => __('Paytrace')],
            ['value' => '$paytrail', 'label' => __('Paytrail')],
            ['value' => '$payture', 'label' => __('Payture')],
            ['value' => '$payway', 'label' => __('Payway')],
            ['value' => '$payu', 'label' => __('Payu')],
            ['value' => '$payulatam', 'label' => __('Payulatam')],
            ['value' => '$payvector', 'label' => __('Payvector')],
            ['value' => '$payza', 'label' => __('Payza')],
            ['value' => '$payzen', 'label' => __('Payzen')],
            ['value' => '$peach_payments', 'label' => __('Peach Payments')],
            ['value' => '$perfect_money', 'label' => __('Perfect Money')],
            ['value' => '$pinpayments', 'label' => __('Pinpayments')],
            ['value' => '$pivotal_payments', 'label' => __('Pivotal Payments')],
            ['value' => '$planet_payment', 'label' => __('Planet Payment')],
            ['value' => '$poli', 'label' => __('Poli')],
            ['value' => '$princeton_payment_solutions', 'label' => __('Princeton Payment Solutions')],
            ['value' => '$prismpay', 'label' => __('Prismpay')],
            ['value' => '$processing', 'label' => __('Processing')],
            ['value' => '$przelewy24', 'label' => __('Przelewy24')],
            ['value' => '$psigate', 'label' => __('Psigate')],
            ['value' => '$pulse', 'label' => __('Pulse')],
            ['value' => '$qiwi', 'label' => __('Qiwi')],
            ['value' => '$quickpay', 'label' => __('Quickpay')],
            ['value' => '$raberil', 'label' => __('Raberil')],
            ['value' => '$radial', 'label' => __('Radial')],
            ['value' => '$rakuten_checkout', 'label' => __('Rakuten Checkout')],
            ['value' => '$rapipago', 'label' => __('Rapipago')],
            ['value' => '$ratepay', 'label' => __('Ratepay')],
            ['value' => '$razorpay', 'label' => __('Razorpay')],
            ['value' => '$rbkmoney', 'label' => __('Rbkmoney')],
            ['value' => '$reach', 'label' => __('Reach')],
            ['value' => '$red_dot_payment', 'label' => __('Red Dot Payment')],
            ['value' => '$rede', 'label' => __('Rede')],
            ['value' => '$redpagos', 'label' => __('Redpagos')],
            ['value' => '$redsys', 'label' => __('Redsys')],
            ['value' => '$rewardspay', 'label' => __('Rewardspay')],
            ['value' => '$rietumu', 'label' => __('Rietumu')],
            ['value' => '$rocketgate', 'label' => __('Rocketgate')],
            ['value' => '$safecharge', 'label' => __('Safecharge')],
            ['value' => '$safetypay', 'label' => __('Safetypay')],
            ['value' => '$sagepay', 'label' => __('Sagepay')],
            ['value' => '$samsung_pay', 'label' => __('Samsung Pay')],
            ['value' => '$securionpay', 'label' => __('Securionpay')],
            ['value' => '$securepay', 'label' => __('Securepay')],
            ['value' => '$sermepa', 'label' => __('Sermepa')],
            ['value' => '$shopify_payments', 'label' => __('Shopify Payments')],
            ['value' => '$simplify_commerce', 'label' => __('Simplify Commerce')],
            ['value' => '$skrill', 'label' => __('Skrill')],
            ['value' => '$smart2pay', 'label' => __('Smart2Pay')],
            ['value' => '$smartcoin', 'label' => __('Smartcoin')],
            ['value' => '$sofort', 'label' => __('Sofort')],
            ['value' => '$splash_payments', 'label' => __('Splash Payments')],
            ['value' => '$sps_decidir', 'label' => __('Sps Decidir')],
            ['value' => '$square', 'label' => __('Square')],
            ['value' => '$stone', 'label' => __('Stone')],
            ['value' => '$stripe', 'label' => __('Stripe')],
            ['value' => '$swedbank', 'label' => __('Swedbank')],
            ['value' => '$synapsepay', 'label' => __('Synapsepay')],
            ['value' => '$telerecargas', 'label' => __('Telerecargas')],
            ['value' => '$tnspay', 'label' => __('Tnspay')],
            ['value' => '$towah', 'label' => __('Towah')],
            ['value' => '$tpaga', 'label' => __('Tpaga')],
            ['value' => '$transact_pro', 'label' => __('Transact Pro')],
            ['value' => '$transfirst', 'label' => __('Transfirst')],
            ['value' => '$trustcommerce', 'label' => __('Trustcommerce')],
            ['value' => '$trustly', 'label' => __('Trustly')],
            ['value' => '$tu_compra', 'label' => __('Tu Compra')],
            ['value' => '$twoc2p', 'label' => __('Twoc2P')],
            ['value' => '$twocheckout', 'label' => __('Twocheckout')],
            ['value' => '$undostres', 'label' => __('Undostres')],
            ['value' => '$unionpay', 'label' => __('Unionpay')],
            ['value' => '$usa_epay', 'label' => __('Usa Epay')],
            ['value' => '$usafill', 'label' => __('Usafill')],
            ['value' => '$vantiv', 'label' => __('Vantiv')],
            ['value' => '$venmo', 'label' => __('Venmo')],
            ['value' => '$veritrans', 'label' => __('Veritrans')],
            ['value' => '$versapay', 'label' => __('Versapay')],
            ['value' => '$vesta', 'label' => __('Vesta')],
            ['value' => '$vindicia', 'label' => __('Vindicia')],
            ['value' => '$virtual_card_services', 'label' => __('Virtual Card Services')],
            ['value' => '$visa', 'label' => __('Visa')],
            ['value' => '$vme', 'label' => __('Vme')],
            ['value' => '$vpos', 'label' => __('Vpos')],
            ['value' => '$webmoney', 'label' => __('Webmoney')],
            ['value' => '$webpay_oneclick', 'label' => __('Webpay Oneclick')],
            ['value' => '$wepay', 'label' => __('Wepay')],
            ['value' => '$western_union', 'label' => __('Western Union')],
            ['value' => '$wirecard', 'label' => __('Wirecard')],
            ['value' => '$worldpay', 'label' => __('Worldpay')],
            ['value' => '$worldspan', 'label' => __('Worldspan')],
            ['value' => '$xipay', 'label' => __('Xipay')],
            ['value' => '$yandex_money', 'label' => __('Yandex Money')],
            ['value' => '$yapstone', 'label' => __('Yapstone')],
            ['value' => '$zeus', 'label' => __('Zeus')],
            ['value' => '$zipmoney', 'label' => __('Zipmoney')],
            ['value' => '$zoop', 'label' => __('Zoop')],
            ['value' => '$zooz_paymentsos', 'label' => __('Zooz Paymentsos')],
        ];
    }
}


